node{

    stage('SCM Checkout')
    {
        git branch: 'main', url: 'https://github.com/srinivas1246/Repository1.git'
    }
    
    stage('Run Docker Compose File')
    {
        sh 'sudo docker-compose build'
        sh 'sudo docker-compose up -d'
    }
  stage('PUSH image to Docker Hub')
    {
      /* withCredentials([string(credentialsId: 'DockerHubPassword', variable: 'DHPWD')]) 
        {
            sh "docker login -u peddireddi1212 -p ${DHPWD}"
        }
        sh 'docker push peddireddi1212/phpmysql_app'
        */
        //docker.withRegistry( 'https://registry.hub.docker.com', 'DockerHubPassword' ) {
             
             sh 'sudo docker login -u "peddireddi1212" -p "fornag0073" docker.io'
             //sh 'sudo docker push peddireddi1212/mysql'
             //sh 'sudo docker push peddireddi1212/job1_web1.0'
             sh 'sudo docker push peddireddi1212/job1_web2.0'
            // sh 'docker push peddireddi1212/mysql'
          
    }
}
